export const images = {
    introImage1: require('../images/IntroImage1.png'),
    introImage2: require('../images/IntroImage2.png'),
    introImage3: require('../images/IntroImage3.png'),
    introImage4: require('../images/IntroImage4.png'),
    logo: require('../images/Logo.png'),
    location: require('../images/Location.png'),
    notificatons: require('./Notification.png'),
    orders: require('./Orders.png'),
    home: require('./Home.png'),
    account: require('./Account.png'),
    towTruck: require('./TowTruck.png'),
    store: require('./Store.png'),
    shoppingCart: require('./ShoppingCart.png'),
    package: require('./Package.png'),
    banner: require('./Banner.png'),
    banner2: require('./banner2.png'),
};
